-- 1. What relationships should `Comment` have?

-- it has a 1 to n relationship with tasks and users, so we add a column user_id and task_id in our comments table.

-- 2. Should `Task` have a `comments` relationship?

-- nope, it is not needed to have a comment column in tasks

-- 3. What should happen to comments when a task is deleted?

-- we should have a trigger to delete all comments with the task_id of the deleted task.


def upgrade():
    op.add_column(
        'tasks',
        sa.Column(
            'priority',
            sa.String(length=20),
            nullable=False,
            server_default='medium'
        )
    )

--

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.dr

--

class Task(Base):
    __tablename__ = "tasks"

    id           = Column(Integer, primary_key=True)
    title        = Column(String(200), nullable=False)
    description  = Column(String(1000))
    status       = Column(String(20), default="open")
    assigned_to  = Column(Integer, ForeignKey("users.id"))
    created_at  = Column(TIMESTAMP, server_default=func.current_timestamp())
    updated_at   = Column(TIMESTAMP, onupdate=func.current_timestamp())
    priority     = Column(String(20), default="medium", nullable=False)
    assignee = relationship("User", back_populates="tasks")
    comments = relationship("Comment", back_populates="task")

    def __repr__(self):
        return f"<Task(id={self.id}, title='{self.title}', status='{self.status}')>"


class Comment(Base):
    __tablename__ = "comments"

    id          = Column(Integer, primary_key=True)
    description = Column(String(200), nullable=False)

    user_id = Column(Integer, ForeignKey("users.id"))
    task_id = Column(Integer, ForeignKey("tasks.id"))

    created_at  = Column(TIMESTAMP, server_default=func.current_timestamp())

    user = relationship("User", back_populates="comments")
    task = relationship("Task", back_populates="comments")

    def __repr__(self):
        return f"<Comment(id={self.id}, user_id={self.user_id}, task_id={self.task_id})>"

---

-- 1. What does `upgrade()` do?

-- upgrade states the changes and updates needed to be executed with the new version

-- 2. What does `downgrade()` do?

-- downgrade has the changes we need to do to roll back to a past version

-- 3. What happens if you downgrade this migration?

-- we would delete the comments table and the column added to tasks

--

-- 1. What happens to the column?

-- the column gets deleted.

-- 2. What happens to the data?

-- all the other data stays as is

--

-- 1. Why use ORM instead of raw SQL?
-- ORMs like SQLAlchemy allow developers to work with Python objects
-- instead of writing raw SQL queries manually. This improves readability,
-- maintainability, portability across databases, and reduces boilerplate code.
-- ORMs also help prevent SQL injection by parameterizing queries automatically.


-- 2. Why use migrations?
-- Migrations allow developers to version-control database schema changes.
-- They make it possible to safely update databases across development,
-- testing, and production environments while keeping schema history consistent.
-- Migrations also make collaboration easier in team projects.


-- 3. When would you rollback?
-- Rollbacks are used when a migration introduces problems such as:
-- broken schemas, incorrect columns, failed deployments, data issues,
-- or application incompatibilities. Rolling back restores the previous
-- stable database state.


-- 4. Difference between add() and commit()?
-- session.add() places an object into SQLAlchemy's session so it can be tracked.
-- It does NOT save data permanently to the database yet.
-- session.commit() finalizes the transaction and permanently writes
-- the pending changes to the database.


-- 5. Why are relationships useful?
-- Relationships allow ORM models to connect related tables using Python objects
-- instead of manual JOIN queries. They simplify navigation between entities,
-- improve code readability, and make working with related data much easier.